/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IU;

import Controladores.ControladorPantallaGestor;
import Controladores.VistaPantallaGestor;
import Logica.Gestor;
import Logica.Pedido;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agust
 */
public class PantallaGestores extends javax.swing.JFrame implements VistaPantallaGestor {
    public ControladorPantallaGestor controlador;
    private VistaPantallaGestor vista;
    /**
     * Creates new form PantallaGestores
     */
    public PantallaGestores(Gestor g) {
        initComponents();
        setVisible(true);
        setTitle("Procesar pedidos");
        controlador = new ControladorPantallaGestor(this, g);
        controlador.setBienvenida();  
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        btnTomarPedido = new javax.swing.JButton();
        lblBienvenidaGestor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPedidos = new javax.swing.JList();
        btnFinalizarPedido = new javax.swing.JButton();
        btnEntregarPedido = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaPedidos.setBackground(new java.awt.Color(204, 204, 255));
        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Descripcion", "Cliente", "FechaHora", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPedidos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaPedidos);

        btnTomarPedido.setBackground(new java.awt.Color(153, 153, 255));
        btnTomarPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTomarPedido.setText("Tomar Pedido");
        btnTomarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarPedidoActionPerformed(evt);
            }
        });

        lblBienvenidaGestor.setBackground(new java.awt.Color(0, 0, 0));
        lblBienvenidaGestor.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblBienvenidaGestor.setText("Gestor: //nombre - //up");

        listPedidos.setBackground(new java.awt.Color(204, 204, 255));
        listPedidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPedidosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPedidos);

        btnFinalizarPedido.setBackground(new java.awt.Color(153, 153, 255));
        btnFinalizarPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFinalizarPedido.setText("Finalizar Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        btnEntregarPedido.setBackground(new java.awt.Color(153, 153, 255));
        btnEntregarPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEntregarPedido.setText("Entregar Pedido");
        btnEntregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarPedidoActionPerformed(evt);
            }
        });

        lblError.setBackground(new java.awt.Color(0, 0, 0));
        lblError.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N

        lblMensaje.setBackground(new java.awt.Color(255, 255, 204));
        lblMensaje.setForeground(new java.awt.Color(0, 0, 0));
        lblMensaje.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBienvenidaGestor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFinalizarPedido)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEntregarPedido))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnTomarPedido))))))
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblBienvenidaGestor)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTomarPedido)
                    .addComponent(lblError))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarPedido)
                    .addComponent(btnEntregarPedido)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listPedidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPedidosValueChanged
        //aca no va nada, me equivoque y no se borrar esto
    }//GEN-LAST:event_listPedidosValueChanged

    private void btnTomarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarPedidoActionPerformed
        //aca va la funcionalidad del boton, aparte de cargarTabla
        tomarPedido();
    }//GEN-LAST:event_btnTomarPedidoActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        // TODO add your handling code here:
        finalizarPedido();
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    private void btnEntregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarPedidoActionPerformed
        // TODO add your handling code here:
        entregarPedido();
    }//GEN-LAST:event_btnEntregarPedidoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        controlador.cerrarVentana();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregarPedido;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnTomarPedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBienvenidaGestor;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JList listPedidos;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables


    @Override
    public void mostrarBienvenida(String nombreCompleto, String unidadProcesadora) {
        lblBienvenidaGestor.setText("Gestor: " + nombreCompleto + " | " + "Unidad Procesadora: " + unidadProcesadora);
    }

    @Override
    public void mostrarPedidos(ArrayList<Pedido> pedidos) {
        listPedidos.setListData(pedidos.toArray());
    }

    public void tomarPedido() {
        int pedidoSeleccionado = listPedidos.getSelectedIndex();
        controlador.tomarPedido(pedidoSeleccionado);
    }

    public void cargarTabla(ArrayList<Pedido> pedidos) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm");

        DefaultTableModel modelo = (DefaultTableModel) tablaPedidos.getModel();
        modelo.setRowCount(0);
        
        //TODO- Idk if you can traverse the list here
        for(Pedido p: pedidos){
            String fechaFormateada = formato.format(p.getFecha());
            modelo.addRow(new Object[]{
                p.getItem().getNombre(),
                p.getComentario(),
                p.getServicio().getCliente().getNombreCompleto(),
                fechaFormateada,
                p.getEstado().getEstado()
            });
        }
        tablaPedidos.setModel(modelo);
    }

    public void finalizarPedido(){
        controlador.finalizarPedidos(tablaPedidos.getSelectedRow());
    }
    
    public void entregarPedido(){
        controlador.entregarPedido(tablaPedidos.getSelectedRow());
    }
    
    @Override
    public void mostrarMensajes(String msg) {
        lblMensaje.setText(msg);
    }

    @Override
    public void cerrarVentana() {
        dispose();
    }
}
